					-- IMPORTING AND CLEANING DATA SET 

ALTER TABLE CHICKEN_REPUBLIC_LAGOS
RENAME TO CRL;

SELECT * FROM CRL;
CREATE TABLE CRL_STAGING LIKE CRL;
INSERT INTO CRL_STAGING SELECT * FROM CRL;
SELECT * FROM CRL_STAGING;

ALTER TABLE CRL_STAGING					 
RENAME COLUMN ï»¿Date TO DATE;

WITH CRL_STAGING_CTE AS 
(
SELECT *,
ROW_NUMBER() OVER(PARTITION BY `DATE`, `Location`, `Product Category`, `Product`, `Quantity Sold`, `Unit Price (NGN)`, `Total Sales (NGN)`, `Profit (NGN)`) AS ROW_NUM
FROM CRL_STAGING
)														-- NO DUPLICATES
SELECT * FROM CRL_STAGING_CTE WHERE ROW_NUM >1;

SELECT DISTINCT (`Product`) FROM CRL_STAGING;			-- NO TYPOGRAPHICAL ERRORS IN INDIVIDUAL COLUMNS

SELECT * FROM CRL_STAGING WHERE `Quantity Sold` IS NULL;		-- NO NULL VALUES

SELECT * FROM CRL_STAGING;

							-- EXPLORATORY DATA ANALYSIS
                            
-- WHICH PRODUCTS CONTRIBUTE TO 80% OF TOTAL REVENUE   
WITH PRODUCT_REVENUE AS(
SELECT PRODUCT, ROUND(SUM(`TOTAL SALES (NGN)`), 2) TOTAL_REVENUE
FROM CRL_STAGING
GROUP BY PRODUCT),
RANKED AS(SELECT PRODUCT,TOTAL_REVENUE,SUM(TOTAL_REVENUE)
OVER () AS OVERALL_REVENUE,
SUM(TOTAL_REVENUE) OVER (ORDER BY TOTAL_REVENUE DESC) CUMULATIVE_REVENUE
FROM PRODUCT_REVENUE
)
SELECT PRODUCT,
TOTAL_REVENUE,
ROUND(TOTAL_REVENUE * 100.0 / OVERALL_REVENUE, 2) AS PRODUCT_PERCENTAGE,
ROUND(CUMULATIVE_REVENUE * 100.0 / OVERALL_REVENUE, 2) AS CUMULATIVE_PERCENTAGE, 
CASE WHEN ROUND(CUMULATIVE_REVENUE * 100.0 / OVERALL_REVENUE, 2) <=80 THEN 'TOP 80%' ELSE 'REMAINING'
END AS CATEGORY
FROM RANKED
ORDER BY TOTAL_REVENUE DESC;

-- WHICH LOCATIONS GENERATE THE HIGHEST REVENUE AND WHICH ARE UNDER-PERFORMING
WITH `LOCATION REVENUE` AS(
SELECT LOCATION, ROUND(SUM(`TOTAL SALES (NGN)`), 2) `TOTAL REVENUE`
FROM CRL_STAGING
GROUP BY LOCATION
)
SELECT LOCATION, `TOTAL REVENUE`,
CASE WHEN `TOTAL REVENUE` < (SELECT AVG(`TOTAL REVENUE`) FROM `LOCATION REVENUE`)
THEN 'UNDERPERFORMING' ELSE 'PERFORMING'
END AS STATUS
FROM `LOCATION REVENUE`
ORDER BY `TOTAL REVENUE` DESC;

-- PRODUCT PERFORMANCE VERSUS PRODUCT PRICING
WITH PRODUCT_PERF AS (
SELECT PRODUCT, SUM(`QUANTITY SOLD`) TOTAL_QUANTITY, ROUND(SUM(`Total Sales (NGN)`), 2) AS TOTAL_REVENUE,
SUM(`Total Sales (NGN)`) * 1.0 / SUM(`QUANTITY SOLD`) AVG_SELLING_PRICE
FROM CRL_STAGING
GROUP BY PRODUCT)
SELECT PRODUCT, ROUND(AVG_SELLING_PRICE, 2) AVG_PRICE, TOTAL_QUANTITY, TOTAL_REVENUE,
CASE WHEN AVG_SELLING_PRICE > (SELECT AVG(AVG_SELLING_PRICE) FROM PRODUCT_PERF)
AND TOTAL_REVENUE > (SELECT AVG(TOTAL_REVENUE) FROM PRODUCT_PERF)
		THEN 'HIGH_PRICE - HIGH PERFORMANCE'
	WHEN AVG_SELLING_PRICE > (SELECT AVG(AVG_SELLING_PRICE) FROM PRODUCT_PERF)
		THEN 'HIGH PRICE - LOW PERFORMAANCE'
	WHEN TOTAL_REVENUE > (SELECT AVG(TOTAL_REVENUE) FROM PRODUCT_PERF)
		THEN 'LOW PRICE - HIGH PERFORMANCE'
ELSE 'LOW PRICE - LOW PERFORMANCE'
END AS CATEGORY
FROM PRODUCT_PERF
ORDER BY AVG_PRICE DESC;

-- HOW DOES SALES CHANGE OVER TIME (MONTHLY SALES CHANGE)
WITH MONTHLY_SALES AS(
SELECT MONTH(DATE) AS SALES_MONTH , SUM(`Quantity Sold`) AS `TOTAL QUANTITY`
FROM CRL_STAGING
GROUP BY SALES_MONTH
)
SELECT SALES_MONTH, `TOTAL QUANTITY`, `TOTAL QUANTITY`- LAG(`TOTAL QUANTITY`) OVER(ORDER BY SALES_MONTH) AS SALES_CHANGE
FROM MONTHLY_SALES
ORDER BY `SALES_MONTH`;

-- HOW DOES SALES CHANGE OVER TIME (PRODUCT CATEGORY SALES CHANGE)
WITH CATEGORY_MONTHLY AS(
SELECT MONTH(DATE) SALES_MONTH, `PRODUCT CATEGORY`, SUM(`Quantity Sold`) AS `TOTAL QUANTITY`
FROM CRL_STAGING
GROUP BY SALES_MONTH, `PRODUCT CATEGORY`
),
RANKED_PRODUCTS AS (
SELECT SALES_MONTH, `PRODUCT CATEGORY`, `TOTAL QUANTITY`,
RANK() OVER(PARTITION BY SALES_MONTH ORDER BY `TOTAL QUANTITY` DESC) AS RANK_
FROM CATEGORY_MONTHLY
)
SELECT *
FROM RANKED_PRODUCTS
ORDER BY SALES_MONTH, RANK_;










                            

                     





